import { defineStore } from 'pinia'

export const useDramaStore = defineStore('views/drama', {
    state: () => ({
        drama_lists: [
            { id: 1, title: "Abyss", genre: "Drama", language: "KH Dub", status: "Ongoing", category: "Mystery", sub_dub: "Dub", country: "korean", description: null, views: '50%', image: "/img/Abyss.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 2, title: "All of Us are Dead", genre: "Romance", language: "KH Dub", status: "Completed", category: "Romantic Comedy", sub_dub: "Sub", country: "korean", description: null, views: '50%', image: "/img/All-of-Us-are-Dead.webp", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 3, title: "Awaken", genre: "Fantasy", language: "KH Dub", status: "Completed", category: "Fantasy Romance", sub_dub: "Sub", country: "korean", description: null, views: '25%', image: "/img/Awaken_2020.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 4, title: "Business Proposal", genre: "Drama", language: "KH Dub", status: "Ongoing", category: "Revenge", sub_dub: "Dub", country: "korean", description: null, views: '50%', image: "/img/business-proposal.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 5, title: "Cheo Yong Drama Series", genre: "Fantasy", language: "KH Dub", status: "Ongoing", category: "Mystery", sub_dub: "Sub", country: "korean", description: null, views: '15%', image: "/img/Cheo_Yong_Drama_Series_2014.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 6, title: "Crash Landing on You", genre: "Action", language: "KH Dub", status: "Ongoing", category: "Military Romance", sub_dub: "Dub", country: "korean", description: null, views: '50%', image: "/img/Crash_Landing_on_You_main_poster.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 7, title: "Doctor Stranger", genre: "Romance", language: "KH Dub", status: "Ongoing", category: "Office Romance", sub_dub: "Sub", country: "korean", description: null, views: '30%', image: "/img/DoctorStranger2014.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 8, title: "Doom at Your Service", genre: "Comedy", language: "KH Dub", status: "Ongoing", category: "Family", sub_dub: "Sub", country: "korean", description: null, views: '50%', image: "/img/Doom_at_your_service.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 9, title: "Happy Ending", genre: "Thriller", language: "Eng Sub", status: "Ongoing", category: "Historical Zombie", sub_dub: "Dub", country: "korean", description: null, views: '50%', image: "/img/happyending.png", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 10, title: "IRIS II", genre: "Romance", language: "Eng Sub", status: "Completed", category: "Superhero", sub_dub: "Sub", country: "korean", description: null, views: '40%', image: "/img/IRIS_II.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 11, title: "Lovely Runner", genre: "Mystery", language: "Eng Sub", status: "Ongoing", category: "Mystery Drama", sub_dub: "Sub", country: "korean", description: null, views: '50%', image: "/img/Lovely Runner.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 12, title: "May It Please the Court", genre: "Thriller", language: "Eng Sub", status: "Completed", category: "Survival", sub_dub: "Dub", country: "korean", description: null, views: '50%', image: "/img/May_It_Please_the_Court_2022.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 13, title: "Mouse", genre: "Romance", language: "Eng Sub", status: "Completed", category: "Healing", sub_dub: "Sub", country: "korean", description: null, views: '50%', image: "/img/Mouse.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 14, title: "Moving", genre: "Action", language: "Eng Sub", status: "Completed", category: "Dark Comedy", sub_dub: "Dub", country: "korean", description: null, views: '30%', image: "/img/Moving.png", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 15, title: "Remember", genre: "Drama", language: "Eng Sub", status: "Ongoing", category: "Slice of Life", sub_dub: "Sub", country: "korean", description: null, views: '60%', image: "/img/Remember_2015.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 16, title: "She Was Pretty", genre: "Historical", language: "Eng Sub", status: "Ongoing", category: "Melodrama", sub_dub: "Dub", country: "korean", description: null, views: '20%', image: "/img/SheWasPretty.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 17, title: "StartUp", genre: "Fantasy", language: "Eng Sub", status: "Ongoing", category: "Parallel Universe", sub_dub: "Sub", country: "korean", description: null, views: '50%', image: "/img/StartUp.webp", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 18, title: "Vincenzo", genre: "Thriller", language: "Eng Sub", status: "Completed", category: "Crime", sub_dub: "Dub", country: "korean", description: null, views: '5%', image: "/img/Vincenzo_2021.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 19, title: "Tales of Demons and Gods", genre: "Romance", language: "Eng Sub", status: "Completed", category: "Psychological", sub_dub: "Sub", country: "chinese", description: null, views: '50%', image: "/img/tales_of_demons and gods.jpg", created_at: "2025-02-20", updated_at: "2025-02-20" },
            { id: 20, title: "Battle Through the Heavens 2", genre: "Anime", language: "Eng Sub", status: "Ongoing", category: "Martial Arts", sub_dub: "Dub", country: "chinese", description: null, views: '15%', image: "/img/battle_through_the_heavens2.jpg", created_at: "2025-02-24", updated_at: "2025-02-24" },
            { id: 21, title: "Tales of Demons and Gods", genre: "Anime", language: "KH Dub", status: "Completed", category: "Cultivation", sub_dub: "Dub", country: "chinese", description: null, views: '30%', image: "/img/tales_of_demons and gods.jpg", created_at: "2025-02-24", updated_at: "2025-02-24" },
            { id: 22, title: "Spirit Sword Sovereign", genre: "Anime", language: "Eng Sub", status: "Ongoing", category: "Cultivation", sub_dub: "Dub", country: "chinese", description: null, views: '50%', image: "/img/Spirit-Sword-Sovereign.webp", created_at: "2025-02-24", updated_at: "2025-02-24" },
            { id: 23, title: "Legend of Xianwu", genre: "Anime", language: "Eng Sub", status: "Completed", category: "Martial Arts", sub_dub: "Dub", country: "chinese", description: null, views: '40%', image: "/img/Legend_of_xianwu.jpg", created_at: "2025-02-24", updated_at: "2025-02-24" },
            { id: 24, title: "Spy x Family", genre: "Anime", language: "KH Dub", status: "Ongoing", category: "Shonen", sub_dub: "Dub", country: "chinese", description: null, views: '50%', image: "/img/spyxfamily.webp", created_at: "2025-02-24", updated_at: "2025-02-24" },
            { id: 25, title: "The Devil Is a Part-Timer S1", genre: "Anime", language: "Eng Sub", status: "Ongoing", category: "Supernatural", sub_dub: "Dub", country: "chinese", description: null, views: '50%', image: "/img/The_Devil_Is_a_Part-TimerS1.png", created_at: "2025-02-24", updated_at: "2025-02-24" },
            { id: 26, title: "Bucchigiri!", genre: "Anime", language: "KH Dub", status: "Completed", category: "Supernatural", sub_dub: "Dub", country: "japanese", description: null, views: '35%', image: "/img/Bucchigiri_!_anime_key_visual.jpg", created_at: "2025-02-24", updated_at: "2025-02-24" },
            { id: 27, title: "Moving", genre: "Sci-Fi", language: "Eng Sub", status: "Ongoing", category: "Superpower", sub_dub: "Dub", country: "korean", description: null, views: '50%', image: "/img/Moving.png", created_at: "2025-02-24", updated_at: "2025-02-24" }
        ]
    }),
    actions: {
        // onLoadDramaLists(){
        //     axios.get()
        // }
    }
})